# Custom Language File for Launcher Customizer

[ejs.app]
title = "Avaloria Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/rapha-blt/avalorialauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "https://instagram.com/avaloriamc"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/rxeC93ZQud"

[ejs.settings]
sourceGithubLink = "https://github.com/rapha-blt/avalorialauncher"
supportLink = "https://github.com/rapha-blt/avalorialauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR AVALORIA"
welcomeDescription = "Découvrez l'incroyable Royaume d'Avaloria, dans son univers médiévalo-magique. Rencontrez de nouvelles personnes en jouant et completez les différentes quêtes proposées. Explorez les nombreux endroits inédits, récoltez vos ressources, construisez vos plus belles fermes automatiques et bâtissez-vous une réputation."
welcomeDescCTA = "Vous y êtes presque."
